---
title: "Taller"
author: "PICT-19-328"
date: "2023-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Desarrollo de técnicas en el campo de análisis de texto asistido por computadora aplicado a la conflictividad social {style="text-align: center"}

##### 1 y 2 de junio de 2023, Mar del Plata {style="text-align: center"}

#### Jueves 1, de 9 a 12:30 h. {style="text-align: justify"}

Desarrollo del paquete ACEP (Análisis Computacional de Eventos de Protesta): mejoramiento de funciones existentes. A cargo del Dr. Agustín Nieto y del Lic. Diego Pacheco

##### Biblio

Lorenzini, J., Kriesi, H., Makarov, P., & Wüest, B. (2022). Protest Event Analysis: Developing a Semiautomated NLP Approach. American Behavioral Scientist, 66(5), 555--577. Links: [original en inglés](https://github.com/agusnieto77/taller_pict_2019/blob/main/biblio/Protest%20Event%20Analysis_en.pdf) y [traducción al español con Google](https://github.com/agusnieto77/taller_pict_2019/blob/main/biblio/Protest%20Event%20Analysis_es.pdf).

##### Ejercicios

#### Jueves 1, de 14 a 17:30 h. {style="text-align: justify"}

Desarrollo del paquete ACEP (Análisis Computacional de Eventos de Protesta): desarrollo de nuevas funciones. A cargo de Rodrigo Fernández y del Dr. Agustín Nieto

##### Biblio

##### Ejercicios

#### Viernes 2, de 9 a 12:30 h. {style="text-align: justify"}

Etiquetado de noticias: hacia el desarrollo de un método basado en el aprendizaje automático supervisado. A cargo de la Lic. Ivana Teijón, el Lic. Nicolás Rabino, la Dra. Luciana Nogueira y el Dr. Pablo Becher

##### Biblio

##### Ejercicios

#### Viernes 2, de 14 a 17:30 h. {style="text-align: justify"}

Extracción de triplet SAO: desarrollo de técnicas para la identificación computacional de sujeto-acción-objeto a partir de BERT (Google) desde Python. A cargo del Dr. Agustín Santella.

##### Biblio

##### Ejercicios
