title: Taller CATA [PICT-328]
subtitle: 1 y 2 de junio de 2023, Mar del Plata
description: Desarrollo de técnicas en el campo de análisis de texto asistido por computadora aplicado a la conflictividad social.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
